// 工程管理データ - 全35ページ分
const scheduleData = {
  taskCycle: [
    "PCデザイン提出",
    "PCデザイン修正依頼提出",
    "PCデザイン修正版提出&確認確定",
    "SPデザイン提出",
    "SPデザイン修正依頼提出",
    "SPデザイン修正版提出&確認確定",
    "PC/SPコーディング提出",
    "PC/SPコーディング修正依頼提出",
    "PC/SPコーディング修正版提出&確認確定",
  ],

  projectInfo: {
    startDate: "2025/07/16(水)",
    endDate: "2025/11/12(水)",
    duration: 18,
    totalPages: 35,
    pagesPerWeek: 5,
    totalMeetings: 18,
  },

  pages: [
    "ジャンルページ（一覧・詳細）",
    "カテゴリページ（一覧・詳細）",
    "選び方ページ - 縦走用アックスの選び方",
    "選び方ページ -登山用軽量ハーネスの活用",
    "選び方ページ -アルトテント/テロステント",
    "新着商品",
    "キャンペーン",
    "限定アイテム",
    "Tech Info TOP",
    "Tech Info 一覧",
    "Tech Info詳細",
    "Tech Info 製品別 一覧",
    "Tech Info 製品別 詳細",
    "商品詳細",
    "マイページ",
    "ご利用にあたって",
    "ご利用ガイド一覧",
    "ご利用ガイド詳細",
    "コーポレートTOP",
    "会社情報",
    "会社情報詳細",
    "取扱店",
    "取扱店一覧",
    "サポート情報",
    "取扱説明書一覧 (PDF)",
    "お問い合わせ",
    "ニュース",
    "重要なお知らせ",
    "ブランドTOPページ",
    "Black Diamondページ",
    "製品一覧",
    "ヒストリー",
    "Ospreyページ",
    "Scarpaページ",
    "Smartwoolページ",
  ],

  weeklyTasks: [
    { week: 1, tasks: 10, meeting: "第1回", date: "2025/07/16(水)" },
    { week: 2, tasks: 15, meeting: "第2回", date: "2025/07/23(水)" },
    { week: 3, tasks: 25, meeting: "第3回", date: "2025/07/30(水)" },
    { week: 4, tasks: 30, meeting: "第4回", date: "2025/08/06(水)" },
    { week: 5, tasks: 40, meeting: "第5回", date: "2025/08/13(水)" },
    { week: 6, tasks: 45, meeting: "第6回", date: "2025/08/20(水)" },
    { week: 7, tasks: 55, meeting: "第7回", date: "2025/08/27(水)" },
    { week: 8, tasks: 50, meeting: "第8回", date: "2025/09/03(水)" },
    { week: 9, tasks: 55, meeting: "第9回", date: "2025/09/10(水)" },
    { week: 10, tasks: 50, meeting: "第10回", date: "2025/09/17(水)" },
    { week: 11, tasks: 55, meeting: "第11回", date: "2025/09/24(水)" },
    { week: 12, tasks: 50, meeting: "第12回", date: "2025/10/01(水)" },
    { week: 13, tasks: 45, meeting: "第13回", date: "2025/10/08(水)" },
    { week: 14, tasks: 35, meeting: "第14回", date: "2025/10/15(水)" },
    { week: 15, tasks: 30, meeting: "第15回", date: "2025/10/22(水)" },
    { week: 16, tasks: 20, meeting: "第16回", date: "2025/10/29(水)" },
    { week: 17, tasks: 15, meeting: "第17回", date: "2025/11/05(水)" },
    { week: 18, tasks: 5, meeting: "第18回(完了)", date: "2025/11/12(水)" },
  ],

  meetings: [
    {
      meetingNo: 1,
      date: "2025/07/16(水)",
      meetingTasks: [
        {
          taskNo: "001",
          page: "ジャンルページ（一覧・詳細）",
          process: "PC設計提出",
        },
        {
          taskNo: "003",
          page: "カテゴリページ（一覧・詳細）",
          process: "PC設計提出",
        },
        {
          taskNo: "005",
          page: "選び方ページ - 縦走用アックスの選び方",
          process: "PC設計提出",
        },
        {
          taskNo: "007",
          page: "選び方ページ -登山用軽量ハーネスの活用",
          process: "PC設計提出",
        },
        {
          taskNo: "009",
          page: "選び方ページ -アルトテント/テロステント",
          process: "PC設計提出",
        },
      ],
      weekTasks: [
        {
          taskNo: "002",
          page: "ジャンルページ（一覧・詳細）",
          process: "PC設計修正依頼提出",
        },
        {
          taskNo: "004",
          page: "カテゴリページ（一覧・詳細）",
          process: "PC設計修正依頼提出",
        },
        {
          taskNo: "006",
          page: "選び方ページ - 縦走用アックスの選び方",
          process: "PC設計修正依頼提出",
        },
        {
          taskNo: "008",
          page: "選び方ページ -登山用軽量ハーネスの活用",
          process: "PC設計修正依頼提出",
        },
        {
          taskNo: "010",
          page: "選び方ページ -アルトテント/テロステント",
          process: "PC設計修正依頼提出",
        },
      ],
      progress: { completed: 0, inProgress: 5, notStarted: 30 },
    },
    {
      meetingNo: 2,
      date: "2025/07/23(水)",
      meetingTasks: [
        {
          taskNo: "011",
          page: "ジャンルページ（一覧・詳細）",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "012",
          page: "カテゴリページ（一覧・詳細）",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "013",
          page: "選び方ページ - 縦走用アックスの選び方",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "014",
          page: "選び方ページ -登山用軽量ハーネスの活用",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "015",
          page: "選び方ページ -アルトテント/テロステント",
          process: "PC設計修正版提出&確認確定",
        },
        { taskNo: "016", page: "新着商品", process: "PC設計提出" },
        { taskNo: "018", page: "キャンペーン", process: "PC設計提出" },
        { taskNo: "020", page: "限定アイテム", process: "PC設計提出" },
        { taskNo: "022", page: "Tech Info TOP", process: "PC設計提出" },
        { taskNo: "024", page: "Tech Info 一覧", process: "PC設計提出" },
      ],
      weekTasks: [
        { taskNo: "017", page: "新着商品", process: "PC設計修正依頼提出" },
        { taskNo: "019", page: "キャンペーン", process: "PC設計修正依頼提出" },
        { taskNo: "021", page: "限定アイテム", process: "PC設計修正依頼提出" },
        { taskNo: "023", page: "Tech Info TOP", process: "PC設計修正依頼提出" },
        {
          taskNo: "025",
          page: "Tech Info 一覧",
          process: "PC設計修正依頼提出",
        },
      ],
      progress: { completed: 0, inProgress: 10, notStarted: 25 },
    },
    {
      meetingNo: 3,
      date: "2025/07/30(水)",
      meetingTasks: [
        {
          taskNo: "026",
          page: "ジャンルページ（一覧・詳細）",
          process: "SP設計提出",
        },
        {
          taskNo: "028",
          page: "カテゴリページ（一覧・詳細）",
          process: "SP設計提出",
        },
        {
          taskNo: "030",
          page: "選び方ページ - 縦走用アックスの選び方",
          process: "SP設計提出",
        },
        {
          taskNo: "032",
          page: "選び方ページ -登山用軽量ハーネスの活用",
          process: "SP設計提出",
        },
        {
          taskNo: "034",
          page: "選び方ページ -アルトテント/テロステント",
          process: "SP設計提出",
        },
        {
          taskNo: "036",
          page: "新着商品",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "037",
          page: "キャンペーン",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "038",
          page: "限定アイテム",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "039",
          page: "Tech Info TOP",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "040",
          page: "Tech Info 一覧",
          process: "PC設計修正版提出&確認確定",
        },
        { taskNo: "041", page: "Tech Info詳細", process: "PC設計提出" },
        { taskNo: "043", page: "Tech Info 製品別 一覧", process: "PC設計提出" },
        { taskNo: "045", page: "Tech Info 製品別 詳細", process: "PC設計提出" },
        { taskNo: "047", page: "商品詳細", process: "PC設計提出" },
        { taskNo: "049", page: "マイページ", process: "PC設計提出" },
      ],
      weekTasks: [
        {
          taskNo: "027",
          page: "ジャンルページ（一覧・詳細）",
          process: "SP設計修正依頼提出",
        },
        {
          taskNo: "029",
          page: "カテゴリページ（一覧・詳細）",
          process: "SP設計修正依頼提出",
        },
        {
          taskNo: "031",
          page: "選び方ページ - 縦走用アックスの選び方",
          process: "SP設計修正依頼提出",
        },
        {
          taskNo: "033",
          page: "選び方ページ -登山用軽量ハーネスの活用",
          process: "SP設計修正依頼提出",
        },
        {
          taskNo: "035",
          page: "選び方ページ -アルトテント/テロステント",
          process: "SP設計修正依頼提出",
        },
        { taskNo: "042", page: "Tech Info詳細", process: "PC設計修正依頼提出" },
        {
          taskNo: "044",
          page: "Tech Info 製品別 一覧",
          process: "PC設計修正依頼提出",
        },
        {
          taskNo: "046",
          page: "Tech Info 製品別 詳細",
          process: "PC設計修正依頼提出",
        },
        { taskNo: "048", page: "商品詳細", process: "PC設計修正依頼提出" },
        { taskNo: "050", page: "マイページ", process: "PC設計修正依頼提出" },
      ],
      progress: { completed: 0, inProgress: 15, notStarted: 20 },
    },
    {
      meetingNo: 4,
      date: "2025/08/06(水)",
      meetingTasks: [
        {
          taskNo: "051",
          page: "ジャンルページ（一覧・詳細）",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "052",
          page: "カテゴリページ（一覧・詳細）",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "053",
          page: "選び方ページ - 縦走用アックスの選び方",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "054",
          page: "選び方ページ -登山用軽量ハーネスの活用",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "055",
          page: "選び方ページ -アルトテント/テロステント",
          process: "SP設計修正版提出&確認確定",
        },
        { taskNo: "056", page: "新着商品", process: "SP設計提出" },
        { taskNo: "058", page: "キャンペーン", process: "SP設計提出" },
        { taskNo: "060", page: "限定アイテム", process: "SP設計提出" },
        { taskNo: "062", page: "Tech Info TOP", process: "SP設計提出" },
        { taskNo: "064", page: "Tech Info 一覧", process: "SP設計提出" },
        {
          taskNo: "066",
          page: "Tech Info詳細",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "067",
          page: "Tech Info 製品別 一覧",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "068",
          page: "Tech Info 製品別 詳細",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "069",
          page: "商品詳細",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "070",
          page: "マイページ",
          process: "PC設計修正版提出&確認確定",
        },
        { taskNo: "071", page: "ご利用にあたって", process: "PC設計提出" },
        { taskNo: "073", page: "ご利用ガイド一覧", process: "PC設計提出" },
        { taskNo: "075", page: "ご利用ガイド詳細", process: "PC設計提出" },
        { taskNo: "077", page: "コーポレートTOP", process: "PC設計提出" },
        { taskNo: "079", page: "会社情報", process: "PC設計提出" },
      ],
      weekTasks: [
        { taskNo: "057", page: "新着商品", process: "SP設計修正依頼提出" },
        { taskNo: "059", page: "キャンペーン", process: "SP設計修正依頼提出" },
        { taskNo: "061", page: "限定アイテム", process: "SP設計修正依頼提出" },
        { taskNo: "063", page: "Tech Info TOP", process: "SP設計修正依頼提出" },
        {
          taskNo: "065",
          page: "Tech Info 一覧",
          process: "SP設計修正依頼提出",
        },
        {
          taskNo: "072",
          page: "ご利用にあたって",
          process: "PC設計修正依頼提出",
        },
        {
          taskNo: "074",
          page: "ご利用ガイド一覧",
          process: "PC設計修正依頼提出",
        },
        {
          taskNo: "076",
          page: "ご利用ガイド詳細",
          process: "PC設計修正依頼提出",
        },
        {
          taskNo: "078",
          page: "コーポレートTOP",
          process: "PC設計修正依頼提出",
        },
        { taskNo: "080", page: "会社情報", process: "PC設計修正依頼提出" },
      ],
      progress: { completed: 0, inProgress: 20, notStarted: 15 },
    },
    {
      meetingNo: 5,
      date: "2025/08/13(水)",
      meetingTasks: [
        {
          taskNo: "081",
          page: "ジャンルページ（一覧・詳細）",
          process: "PCデザイン提出",
        },
        {
          taskNo: "083",
          page: "カテゴリページ（一覧・詳細）",
          process: "PCデザイン提出",
        },
        {
          taskNo: "085",
          page: "選び方ページ - 縦走用アックスの選び方",
          process: "PCデザイン提出",
        },
        {
          taskNo: "087",
          page: "選び方ページ -登山用軽量ハーネスの活用",
          process: "PCデザイン提出",
        },
        {
          taskNo: "089",
          page: "選び方ページ -アルトテント/テロステント",
          process: "PCデザイン提出",
        },
        {
          taskNo: "091",
          page: "新着商品",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "092",
          page: "キャンペーン",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "093",
          page: "限定アイテム",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "094",
          page: "Tech Info TOP",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "095",
          page: "Tech Info 一覧",
          process: "SP設計修正版提出&確認確定",
        },
        { taskNo: "096", page: "Tech Info詳細", process: "SP設計提出" },
        { taskNo: "098", page: "Tech Info 製品別 一覧", process: "SP設計提出" },
        { taskNo: "100", page: "Tech Info 製品別 詳細", process: "SP設計提出" },
        { taskNo: "102", page: "商品詳細", process: "SP設計提出" },
        { taskNo: "104", page: "マイページ", process: "SP設計提出" },
        {
          taskNo: "106",
          page: "ご利用にあたって",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "107",
          page: "ご利用ガイド一覧",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "108",
          page: "ご利用ガイド詳細",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "109",
          page: "コーポレートTOP",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "110",
          page: "会社情報",
          process: "PC設計修正版提出&確認確定",
        },
        { taskNo: "111", page: "会社情報詳細", process: "PC設計提出" },
        { taskNo: "113", page: "取扱店", process: "PC設計提出" },
        { taskNo: "115", page: "取扱店一覧", process: "PC設計提出" },
        { taskNo: "117", page: "サポート情報", process: "PC設計提出" },
        { taskNo: "119", page: "取扱説明書一覧 (PDF)", process: "PC設計提出" },
      ],
      weekTasks: [
        {
          taskNo: "082",
          page: "ジャンルページ（一覧・詳細）",
          process: "PCデザイン修正依頼提出",
        },
        {
          taskNo: "084",
          page: "カテゴリページ（一覧・詳細）",
          process: "PCデザイン修正依頼提出",
        },
        {
          taskNo: "086",
          page: "選び方ページ - 縦走用アックスの選び方",
          process: "PCデザイン修正依頼提出",
        },
        {
          taskNo: "088",
          page: "選び方ページ -登山用軽量ハーネスの活用",
          process: "PCデザイン修正依頼提出",
        },
        {
          taskNo: "090",
          page: "選び方ページ -アルトテント/テロステント",
          process: "PCデザイン修正依頼提出",
        },
        { taskNo: "097", page: "Tech Info詳細", process: "SP設計修正依頼提出" },
        {
          taskNo: "099",
          page: "Tech Info 製品別 一覧",
          process: "SP設計修正依頼提出",
        },
        {
          taskNo: "101",
          page: "Tech Info 製品別 詳細",
          process: "SP設計修正依頼提出",
        },
        { taskNo: "103", page: "商品詳細", process: "SP設計修正依頼提出" },
        { taskNo: "105", page: "マイページ", process: "SP設計修正依頼提出" },
        { taskNo: "112", page: "会社情報詳細", process: "PC設計修正依頼提出" },
        { taskNo: "114", page: "取扱店", process: "PC設計修正依頼提出" },
        { taskNo: "116", page: "取扱店一覧", process: "PC設計修正依頼提出" },
        { taskNo: "118", page: "サポート情報", process: "PC設計修正依頼提出" },
        {
          taskNo: "120",
          page: "取扱説明書一覧 (PDF)",
          process: "PC設計修正依頼提出",
        },
      ],
      progress: { completed: 0, inProgress: 25, notStarted: 10 },
    },
    {
      meetingNo: 6,
      date: "2025/08/20(水)",
      meetingTasks: [
        {
          taskNo: "121",
          page: "ジャンルページ（一覧・詳細）",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "122",
          page: "カテゴリページ（一覧・詳細）",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "123",
          page: "選び方ページ - 縦走用アックスの選び方",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "124",
          page: "選び方ページ -登山用軽量ハーネスの活用",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "125",
          page: "選び方ページ -アルトテント/テロステント",
          process: "PCデザイン修正版提出&確認確定",
        },
        { taskNo: "126", page: "新着商品", process: "PCデザイン提出" },
        { taskNo: "128", page: "キャンペーン", process: "PCデザイン提出" },
        { taskNo: "130", page: "限定アイテム", process: "PCデザイン提出" },
        { taskNo: "132", page: "Tech Info TOP", process: "PCデザイン提出" },
        { taskNo: "134", page: "Tech Info 一覧", process: "PCデザイン提出" },
        {
          taskNo: "136",
          page: "Tech Info詳細",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "137",
          page: "Tech Info 製品別 一覧",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "138",
          page: "Tech Info 製品別 詳細",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "139",
          page: "商品詳細",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "140",
          page: "マイページ",
          process: "SP設計修正版提出&確認確定",
        },
        { taskNo: "141", page: "ご利用にあたって", process: "SP設計提出" },
        { taskNo: "143", page: "ご利用ガイド一覧", process: "SP設計提出" },
        { taskNo: "145", page: "ご利用ガイド詳細", process: "SP設計提出" },
        { taskNo: "147", page: "コーポレートTOP", process: "SP設計提出" },
        { taskNo: "149", page: "会社情報", process: "SP設計提出" },
        {
          taskNo: "151",
          page: "会社情報詳細",
          process: "PC設計修正版提出&確認確定",
        },
        { taskNo: "152", page: "取扱店", process: "PC設計修正版提出&確認確定" },
        {
          taskNo: "153",
          page: "取扱店一覧",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "154",
          page: "サポート情報",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "155",
          page: "取扱説明書一覧 (PDF)",
          process: "PC設計修正版提出&確認確定",
        },
        { taskNo: "156", page: "お問い合わせ", process: "PC設計提出" },
        { taskNo: "158", page: "ニュース", process: "PC設計提出" },
        { taskNo: "160", page: "重要なお知らせ", process: "PC設計提出" },
        { taskNo: "162", page: "ブランドTOPページ", process: "PC設計提出" },
        { taskNo: "164", page: "Black Diamondページ", process: "PC設計提出" },
      ],
      weekTasks: [
        { taskNo: "127", page: "新着商品", process: "PCデザイン修正依頼提出" },
        {
          taskNo: "129",
          page: "キャンペーン",
          process: "PCデザイン修正依頼提出",
        },
        {
          taskNo: "131",
          page: "限定アイテム",
          process: "PCデザイン修正依頼提出",
        },
        {
          taskNo: "133",
          page: "Tech Info TOP",
          process: "PCデザイン修正依頼提出",
        },
        {
          taskNo: "135",
          page: "Tech Info 一覧",
          process: "PCデザイン修正依頼提出",
        },
        {
          taskNo: "142",
          page: "ご利用にあたって",
          process: "SP設計修正依頼提出",
        },
        {
          taskNo: "144",
          page: "ご利用ガイド一覧",
          process: "SP設計修正依頼提出",
        },
        {
          taskNo: "146",
          page: "ご利用ガイド詳細",
          process: "SP設計修正依頼提出",
        },
        {
          taskNo: "148",
          page: "コーポレートTOP",
          process: "SP設計修正依頼提出",
        },
        { taskNo: "150", page: "会社情報", process: "SP設計修正依頼提出" },
        { taskNo: "157", page: "お問い合わせ", process: "PC設計修正依頼提出" },
        { taskNo: "159", page: "ニュース", process: "PC設計修正依頼提出" },
        {
          taskNo: "161",
          page: "重要なお知らせ",
          process: "PC設計修正依頼提出",
        },
        {
          taskNo: "163",
          page: "ブランドTOPページ",
          process: "PC設計修正依頼提出",
        },
        {
          taskNo: "165",
          page: "Black Diamondページ",
          process: "PC設計修正依頼提出",
        },
      ],
      progress: { completed: 0, inProgress: 30, notStarted: 5 },
    },
    {
      meetingNo: 7,
      date: "2025/08/27(水)",
      meetingTasks: [
        {
          taskNo: "166",
          page: "ジャンルページ（一覧・詳細）",
          process: "SPデザイン提出",
        },
        {
          taskNo: "168",
          page: "カテゴリページ（一覧・詳細）",
          process: "SPデザイン提出",
        },
        {
          taskNo: "170",
          page: "選び方ページ - 縦走用アックスの選び方",
          process: "SPデザイン提出",
        },
        {
          taskNo: "172",
          page: "選び方ページ -登山用軽量ハーネスの活用",
          process: "SPデザイン提出",
        },
        {
          taskNo: "174",
          page: "選び方ページ -アルトテント/テロステント",
          process: "SPデザイン提出",
        },
        {
          taskNo: "176",
          page: "新着商品",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "177",
          page: "キャンペーン",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "178",
          page: "限定アイテム",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "179",
          page: "Tech Info TOP",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "180",
          page: "Tech Info 一覧",
          process: "PCデザイン修正版提出&確認確定",
        },
        { taskNo: "181", page: "Tech Info詳細", process: "PCデザイン提出" },
        {
          taskNo: "183",
          page: "Tech Info 製品別 一覧",
          process: "PCデザイン提出",
        },
        {
          taskNo: "185",
          page: "Tech Info 製品別 詳細",
          process: "PCデザイン提出",
        },
        { taskNo: "187", page: "商品詳細", process: "PCデザイン提出" },
        { taskNo: "189", page: "マイページ", process: "PCデザイン提出" },
        {
          taskNo: "191",
          page: "ご利用にあたって",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "192",
          page: "ご利用ガイド一覧",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "193",
          page: "ご利用ガイド詳細",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "194",
          page: "コーポレートTOP",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "195",
          page: "会社情報",
          process: "SP設計修正版提出&確認確定",
        },
        { taskNo: "196", page: "会社情報詳細", process: "SP設計提出" },
        { taskNo: "198", page: "取扱店", process: "SP設計提出" },
        { taskNo: "200", page: "取扱店一覧", process: "SP設計提出" },
        { taskNo: "202", page: "サポート情報", process: "SP設計提出" },
        { taskNo: "204", page: "取扱説明書一覧 (PDF)", process: "SP設計提出" },
        {
          taskNo: "206",
          page: "お問い合わせ",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "207",
          page: "ニュース",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "208",
          page: "重要なお知らせ",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "209",
          page: "ブランドTOPページ",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "210",
          page: "Black Diamondページ",
          process: "PC設計修正版提出&確認確定",
        },
        { taskNo: "211", page: "製品一覧", process: "PC設計提出" },
        { taskNo: "213", page: "ヒストリー", process: "PC設計提出" },
        { taskNo: "215", page: "Ospreyページ", process: "PC設計提出" },
        { taskNo: "217", page: "Scarpaページ", process: "PC設計提出" },
        { taskNo: "219", page: "Smartwoolページ", process: "PC設計提出" },
      ],
      weekTasks: [
        {
          taskNo: "167",
          page: "ジャンルページ（一覧・詳細）",
          process: "SPデザイン修正依頼提出",
        },
        {
          taskNo: "169",
          page: "カテゴリページ（一覧・詳細）",
          process: "SPデザイン修正依頼提出",
        },
        {
          taskNo: "171",
          page: "選び方ページ - 縦走用アックスの選び方",
          process: "SPデザイン修正依頼提出",
        },
        {
          taskNo: "173",
          page: "選び方ページ -登山用軽量ハーネスの活用",
          process: "SPデザイン修正依頼提出",
        },
        {
          taskNo: "175",
          page: "選び方ページ -アルトテント/テロステント",
          process: "SPデザイン修正依頼提出",
        },
        {
          taskNo: "182",
          page: "Tech Info詳細",
          process: "PCデザイン修正依頼提出",
        },
        {
          taskNo: "184",
          page: "Tech Info 製品別 一覧",
          process: "PCデザイン修正依頼提出",
        },
        {
          taskNo: "186",
          page: "Tech Info 製品別 詳細",
          process: "PCデザイン修正依頼提出",
        },
        { taskNo: "188", page: "商品詳細", process: "PCデザイン修正依頼提出" },
        {
          taskNo: "190",
          page: "マイページ",
          process: "PCデザイン修正依頼提出",
        },
        { taskNo: "197", page: "会社情報詳細", process: "SP設計修正依頼提出" },
        { taskNo: "199", page: "取扱店", process: "SP設計修正依頼提出" },
        { taskNo: "201", page: "取扱店一覧", process: "SP設計修正依頼提出" },
        { taskNo: "203", page: "サポート情報", process: "SP設計修正依頼提出" },
        {
          taskNo: "205",
          page: "取扱説明書一覧 (PDF)",
          process: "SP設計修正依頼提出",
        },
        { taskNo: "212", page: "製品一覧", process: "PC設計修正依頼提出" },
        { taskNo: "214", page: "ヒストリー", process: "PC設計修正依頼提出" },
        { taskNo: "216", page: "Ospreyページ", process: "PC設計修正依頼提出" },
        { taskNo: "218", page: "Scarpaページ", process: "PC設計修正依頼提出" },
        {
          taskNo: "220",
          page: "Smartwoolページ",
          process: "PC設計修正依頼提出",
        },
      ],
      progress: { completed: 0, inProgress: 35, notStarted: 0 },
    },
    {
      meetingNo: 8,
      date: "2025/09/03(水)",
      meetingTasks: [
        {
          taskNo: "221",
          page: "ジャンルページ（一覧・詳細）",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "222",
          page: "カテゴリページ（一覧・詳細）",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "223",
          page: "選び方ページ - 縦走用アックスの選び方",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "224",
          page: "選び方ページ -登山用軽量ハーネスの活用",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "225",
          page: "選び方ページ -アルトテント/テロステント",
          process: "SPデザイン修正版提出&確認確定",
        },
        { taskNo: "226", page: "新着商品", process: "SPデザイン提出" },
        { taskNo: "228", page: "キャンペーン", process: "SPデザイン提出" },
        { taskNo: "230", page: "限定アイテム", process: "SPデザイン提出" },
        { taskNo: "232", page: "Tech Info TOP", process: "SPデザイン提出" },
        { taskNo: "234", page: "Tech Info 一覧", process: "SPデザイン提出" },
        {
          taskNo: "236",
          page: "Tech Info詳細",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "237",
          page: "Tech Info 製品別 一覧",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "238",
          page: "Tech Info 製品別 詳細",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "239",
          page: "商品詳細",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "240",
          page: "マイページ",
          process: "PCデザイン修正版提出&確認確定",
        },
        { taskNo: "241", page: "ご利用にあたって", process: "PCデザイン提出" },
        { taskNo: "243", page: "ご利用ガイド一覧", process: "PCデザイン提出" },
        { taskNo: "245", page: "ご利用ガイド詳細", process: "PCデザイン提出" },
        { taskNo: "247", page: "コーポレートTOP", process: "PCデザイン提出" },
        { taskNo: "249", page: "会社情報", process: "PCデザイン提出" },
        {
          taskNo: "251",
          page: "会社情報詳細",
          process: "SP設計修正版提出&確認確定",
        },
        { taskNo: "252", page: "取扱店", process: "SP設計修正版提出&確認確定" },
        {
          taskNo: "253",
          page: "取扱店一覧",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "254",
          page: "サポート情報",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "255",
          page: "取扱説明書一覧 (PDF)",
          process: "SP設計修正版提出&確認確定",
        },
        { taskNo: "256", page: "お問い合わせ", process: "SP設計提出" },
        { taskNo: "258", page: "ニュース", process: "SP設計提出" },
        { taskNo: "260", page: "重要なお知らせ", process: "SP設計提出" },
        { taskNo: "262", page: "ブランドTOPページ", process: "SP設計提出" },
        { taskNo: "264", page: "Black Diamondページ", process: "SP設計提出" },
        {
          taskNo: "266",
          page: "製品一覧",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "267",
          page: "ヒストリー",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "268",
          page: "Ospreyページ",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "269",
          page: "Scarpaページ",
          process: "PC設計修正版提出&確認確定",
        },
        {
          taskNo: "270",
          page: "Smartwoolページ",
          process: "PC設計修正版提出&確認確定",
        },
      ],
      weekTasks: [
        { taskNo: "227", page: "新着商品", process: "SPデザイン修正依頼提出" },
        {
          taskNo: "229",
          page: "キャンペーン",
          process: "SPデザイン修正依頼提出",
        },
        {
          taskNo: "231",
          page: "限定アイテム",
          process: "SPデザイン修正依頼提出",
        },
        {
          taskNo: "233",
          page: "Tech Info TOP",
          process: "SPデザイン修正依頼提出",
        },
        {
          taskNo: "235",
          page: "Tech Info 一覧",
          process: "SPデザイン修正依頼提出",
        },
        {
          taskNo: "242",
          page: "ご利用にあたって",
          process: "PCデザイン修正依頼提出",
        },
        {
          taskNo: "244",
          page: "ご利用ガイド一覧",
          process: "PCデザイン修正依頼提出",
        },
        {
          taskNo: "246",
          page: "ご利用ガイド詳細",
          process: "PCデザイン修正依頼提出",
        },
        {
          taskNo: "248",
          page: "コーポレートTOP",
          process: "PCデザイン修正依頼提出",
        },
        { taskNo: "250", page: "会社情報", process: "PCデザイン修正依頼提出" },
        { taskNo: "257", page: "お問い合わせ", process: "SP設計修正依頼提出" },
        { taskNo: "259", page: "ニュース", process: "SP設計修正依頼提出" },
        {
          taskNo: "261",
          page: "重要なお知らせ",
          process: "SP設計修正依頼提出",
        },
        {
          taskNo: "263",
          page: "ブランドTOPページ",
          process: "SP設計修正依頼提出",
        },
        {
          taskNo: "265",
          page: "Black Diamondページ",
          process: "SP設計修正依頼提出",
        },
      ],
      progress: { completed: 0, inProgress: 35, notStarted: 0 },
    },
    {
      meetingNo: 9,
      date: "2025/09/10(水)",
      meetingTasks: [
        {
          taskNo: "271",
          page: "ジャンルページ（一覧・詳細）",
          process: "PCコーディング提出",
        },
        {
          taskNo: "273",
          page: "カテゴリページ（一覧・詳細）",
          process: "PCコーディング提出",
        },
        {
          taskNo: "275",
          page: "選び方ページ - 縦走用アックスの選び方",
          process: "PCコーディング提出",
        },
        {
          taskNo: "277",
          page: "選び方ページ -登山用軽量ハーネスの活用",
          process: "PCコーディング提出",
        },
        {
          taskNo: "279",
          page: "選び方ページ -アルトテント/テロステント",
          process: "PCコーディング提出",
        },
        {
          taskNo: "281",
          page: "新着商品",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "282",
          page: "キャンペーン",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "283",
          page: "限定アイテム",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "284",
          page: "Tech Info TOP",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "285",
          page: "Tech Info 一覧",
          process: "SPデザイン修正版提出&確認確定",
        },
        { taskNo: "286", page: "Tech Info詳細", process: "SPデザイン提出" },
        {
          taskNo: "288",
          page: "Tech Info 製品別 一覧",
          process: "SPデザイン提出",
        },
        {
          taskNo: "290",
          page: "Tech Info 製品別 詳細",
          process: "SPデザイン提出",
        },
        { taskNo: "292", page: "商品詳細", process: "SPデザイン提出" },
        { taskNo: "294", page: "マイページ", process: "SPデザイン提出" },
        {
          taskNo: "296",
          page: "ご利用にあたって",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "297",
          page: "ご利用ガイド一覧",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "298",
          page: "ご利用ガイド詳細",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "299",
          page: "コーポレートTOP",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "300",
          page: "会社情報",
          process: "PCデザイン修正版提出&確認確定",
        },
        { taskNo: "301", page: "会社情報詳細", process: "PCデザイン提出" },
        { taskNo: "303", page: "取扱店", process: "PCデザイン提出" },
        { taskNo: "305", page: "取扱店一覧", process: "PCデザイン提出" },
        { taskNo: "307", page: "サポート情報", process: "PCデザイン提出" },
        {
          taskNo: "309",
          page: "取扱説明書一覧 (PDF)",
          process: "PCデザイン提出",
        },
        {
          taskNo: "311",
          page: "お問い合わせ",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "312",
          page: "ニュース",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "313",
          page: "重要なお知らせ",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "314",
          page: "ブランドTOPページ",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "315",
          page: "Black Diamondページ",
          process: "SP設計修正版提出&確認確定",
        },
        { taskNo: "316", page: "製品一覧", process: "SP設計提出" },
        { taskNo: "318", page: "ヒストリー", process: "SP設計提出" },
        { taskNo: "320", page: "Ospreyページ", process: "SP設計提出" },
        { taskNo: "322", page: "Scarpaページ", process: "SP設計提出" },
        { taskNo: "324", page: "Smartwoolページ", process: "SP設計提出" },
      ],
      weekTasks: [
        {
          taskNo: "272",
          page: "ジャンルページ（一覧・詳細）",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "274",
          page: "カテゴリページ（一覧・詳細）",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "276",
          page: "選び方ページ - 縦走用アックスの選び方",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "278",
          page: "選び方ページ -登山用軽量ハーネスの活用",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "280",
          page: "選び方ページ -アルトテント/テロステント",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "287",
          page: "Tech Info詳細",
          process: "SPデザイン修正依頼提出",
        },
        {
          taskNo: "289",
          page: "Tech Info 製品別 一覧",
          process: "SPデザイン修正依頼提出",
        },
        {
          taskNo: "291",
          page: "Tech Info 製品別 詳細",
          process: "SPデザイン修正依頼提出",
        },
        { taskNo: "293", page: "商品詳細", process: "SPデザイン修正依頼提出" },
        {
          taskNo: "295",
          page: "マイページ",
          process: "SPデザイン修正依頼提出",
        },
        {
          taskNo: "302",
          page: "会社情報詳細",
          process: "PCデザイン修正依頼提出",
        },
        { taskNo: "304", page: "取扱店", process: "PCデザイン修正依頼提出" },
        {
          taskNo: "306",
          page: "取扱店一覧",
          process: "PCデザイン修正依頼提出",
        },
        {
          taskNo: "308",
          page: "サポート情報",
          process: "PCデザイン修正依頼提出",
        },
        {
          taskNo: "310",
          page: "取扱説明書一覧 (PDF)",
          process: "PCデザイン修正依頼提出",
        },
        { taskNo: "317", page: "製品一覧", process: "SP設計修正依頼提出" },
        { taskNo: "319", page: "ヒストリー", process: "SP設計修正依頼提出" },
        { taskNo: "321", page: "Ospreyページ", process: "SP設計修正依頼提出" },
        { taskNo: "323", page: "Scarpaページ", process: "SP設計修正依頼提出" },
        {
          taskNo: "325",
          page: "Smartwoolページ",
          process: "SP設計修正依頼提出",
        },
      ],
      progress: { completed: 0, inProgress: 35, notStarted: 0 },
    },
    {
      meetingNo: 10,
      date: "2025/09/17(水)",
      meetingTasks: [
        {
          taskNo: "326",
          page: "ジャンルページ（一覧・詳細）",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "327",
          page: "カテゴリページ（一覧・詳細）",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "328",
          page: "選び方ページ - 縦走用アックスの選び方",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "329",
          page: "選び方ページ -登山用軽量ハーネスの活用",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "330",
          page: "選び方ページ -アルトテント/テロステント",
          process: "PCコーディング修正版提出&確認確定",
        },
        { taskNo: "331", page: "新着商品", process: "PCコーディング提出" },
        { taskNo: "333", page: "キャンペーン", process: "PCコーディング提出" },
        { taskNo: "335", page: "限定アイテム", process: "PCコーディング提出" },
        { taskNo: "337", page: "Tech Info TOP", process: "PCコーディング提出" },
        {
          taskNo: "339",
          page: "Tech Info 一覧",
          process: "PCコーディング提出",
        },
        {
          taskNo: "341",
          page: "Tech Info詳細",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "342",
          page: "Tech Info 製品別 一覧",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "343",
          page: "Tech Info 製品別 詳細",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "344",
          page: "商品詳細",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "345",
          page: "マイページ",
          process: "SPデザイン修正版提出&確認確定",
        },
        { taskNo: "346", page: "ご利用にあたって", process: "SPデザイン提出" },
        { taskNo: "348", page: "ご利用ガイド一覧", process: "SPデザイン提出" },
        { taskNo: "350", page: "ご利用ガイド詳細", process: "SPデザイン提出" },
        { taskNo: "352", page: "コーポレートTOP", process: "SPデザイン提出" },
        { taskNo: "354", page: "会社情報", process: "SPデザイン提出" },
        {
          taskNo: "356",
          page: "会社情報詳細",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "357",
          page: "取扱店",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "358",
          page: "取扱店一覧",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "359",
          page: "サポート情報",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "360",
          page: "取扱説明書一覧 (PDF)",
          process: "PCデザイン修正版提出&確認確定",
        },
        { taskNo: "361", page: "お問い合わせ", process: "PCデザイン提出" },
        { taskNo: "363", page: "ニュース", process: "PCデザイン提出" },
        { taskNo: "365", page: "重要なお知らせ", process: "PCデザイン提出" },
        { taskNo: "367", page: "ブランドTOPページ", process: "PCデザイン提出" },
        {
          taskNo: "369",
          page: "Black Diamondページ",
          process: "PCデザイン提出",
        },
        {
          taskNo: "371",
          page: "製品一覧",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "372",
          page: "ヒストリー",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "373",
          page: "Ospreyページ",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "374",
          page: "Scarpaページ",
          process: "SP設計修正版提出&確認確定",
        },
        {
          taskNo: "375",
          page: "Smartwoolページ",
          process: "SP設計修正版提出&確認確定",
        },
      ],
      weekTasks: [
        {
          taskNo: "332",
          page: "新着商品",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "334",
          page: "キャンペーン",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "336",
          page: "限定アイテム",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "338",
          page: "Tech Info TOP",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "340",
          page: "Tech Info 一覧",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "347",
          page: "ご利用にあたって",
          process: "SPデザイン修正依頼提出",
        },
        {
          taskNo: "349",
          page: "ご利用ガイド一覧",
          process: "SPデザイン修正依頼提出",
        },
        {
          taskNo: "351",
          page: "ご利用ガイド詳細",
          process: "SPデザイン修正依頼提出",
        },
        {
          taskNo: "353",
          page: "コーポレートTOP",
          process: "SPデザイン修正依頼提出",
        },
        { taskNo: "355", page: "会社情報", process: "SPデザイン修正依頼提出" },
        {
          taskNo: "362",
          page: "お問い合わせ",
          process: "PCデザイン修正依頼提出",
        },
        { taskNo: "364", page: "ニュース", process: "PCデザイン修正依頼提出" },
        {
          taskNo: "366",
          page: "重要なお知らせ",
          process: "PCデザイン修正依頼提出",
        },
        {
          taskNo: "368",
          page: "ブランドTOPページ",
          process: "PCデザイン修正依頼提出",
        },
        {
          taskNo: "370",
          page: "Black Diamondページ",
          process: "PCデザイン修正依頼提出",
        },
      ],
      progress: { completed: 0, inProgress: 35, notStarted: 0 },
    },
    {
      meetingNo: 11,
      date: "2025/09/24(水)",
      meetingTasks: [
        {
          taskNo: "376",
          page: "ジャンルページ（一覧・詳細）",
          process: "SPコーディング提出",
        },
        {
          taskNo: "378",
          page: "カテゴリページ（一覧・詳細）",
          process: "SPコーディング提出",
        },
        {
          taskNo: "380",
          page: "選び方ページ - 縦走用アックスの選び方",
          process: "SPコーディング提出",
        },
        {
          taskNo: "382",
          page: "選び方ページ -登山用軽量ハーネスの活用",
          process: "SPコーディング提出",
        },
        {
          taskNo: "384",
          page: "選び方ページ -アルトテント/テロステント",
          process: "SPコーディング提出",
        },
        {
          taskNo: "386",
          page: "新着商品",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "387",
          page: "キャンペーン",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "388",
          page: "限定アイテム",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "389",
          page: "Tech Info TOP",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "390",
          page: "Tech Info 一覧",
          process: "PCコーディング修正版提出&確認確定",
        },
        { taskNo: "391", page: "Tech Info詳細", process: "PCコーディング提出" },
        {
          taskNo: "393",
          page: "Tech Info 製品別 一覧",
          process: "PCコーディング提出",
        },
        {
          taskNo: "395",
          page: "Tech Info 製品別 詳細",
          process: "PCコーディング提出",
        },
        { taskNo: "397", page: "商品詳細", process: "PCコーディング提出" },
        { taskNo: "399", page: "マイページ", process: "PCコーディング提出" },
        {
          taskNo: "401",
          page: "ご利用にあたって",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "402",
          page: "ご利用ガイド一覧",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "403",
          page: "ご利用ガイド詳細",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "404",
          page: "コーポレートTOP",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "405",
          page: "会社情報",
          process: "SPデザイン修正版提出&確認確定",
        },
        { taskNo: "406", page: "会社情報詳細", process: "SPデザイン提出" },
        { taskNo: "408", page: "取扱店", process: "SPデザイン提出" },
        { taskNo: "410", page: "取扱店一覧", process: "SPデザイン提出" },
        { taskNo: "412", page: "サポート情報", process: "SPデザイン提出" },
        {
          taskNo: "414",
          page: "取扱説明書一覧 (PDF)",
          process: "SPデザイン提出",
        },
        {
          taskNo: "416",
          page: "お問い合わせ",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "417",
          page: "ニュース",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "418",
          page: "重要なお知らせ",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "419",
          page: "ブランドTOPページ",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "420",
          page: "Black Diamondページ",
          process: "PCデザイン修正版提出&確認確定",
        },
        { taskNo: "421", page: "製品一覧", process: "PCデザイン提出" },
        { taskNo: "423", page: "ヒストリー", process: "PCデザイン提出" },
        { taskNo: "425", page: "Ospreyページ", process: "PCデザイン提出" },
        { taskNo: "427", page: "Scarpaページ", process: "PCデザイン提出" },
        { taskNo: "429", page: "Smartwoolページ", process: "PCデザイン提出" },
      ],
      weekTasks: [
        {
          taskNo: "377",
          page: "ジャンルページ（一覧・詳細）",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "379",
          page: "カテゴリページ（一覧・詳細）",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "381",
          page: "選び方ページ - 縦走用アックスの選び方",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "383",
          page: "選び方ページ -登山用軽量ハーネスの活用",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "385",
          page: "選び方ページ -アルトテント/テロステント",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "392",
          page: "Tech Info詳細",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "394",
          page: "Tech Info 製品別 一覧",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "396",
          page: "Tech Info 製品別 詳細",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "398",
          page: "商品詳細",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "400",
          page: "マイページ",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "407",
          page: "会社情報詳細",
          process: "SPデザイン修正依頼提出",
        },
        { taskNo: "409", page: "取扱店", process: "SPデザイン修正依頼提出" },
        {
          taskNo: "411",
          page: "取扱店一覧",
          process: "SPデザイン修正依頼提出",
        },
        {
          taskNo: "413",
          page: "サポート情報",
          process: "SPデザイン修正依頼提出",
        },
        {
          taskNo: "415",
          page: "取扱説明書一覧 (PDF)",
          process: "SPデザイン修正依頼提出",
        },
        { taskNo: "422", page: "製品一覧", process: "PCデザイン修正依頼提出" },
        {
          taskNo: "424",
          page: "ヒストリー",
          process: "PCデザイン修正依頼提出",
        },
        {
          taskNo: "426",
          page: "Ospreyページ",
          process: "PCデザイン修正依頼提出",
        },
        {
          taskNo: "428",
          page: "Scarpaページ",
          process: "PCデザイン修正依頼提出",
        },
        {
          taskNo: "430",
          page: "Smartwoolページ",
          process: "PCデザイン修正依頼提出",
        },
      ],
      progress: { completed: 0, inProgress: 35, notStarted: 0 },
    },
    {
      meetingNo: 12,
      date: "2025/10/01(水)",
      meetingTasks: [
        {
          taskNo: "431",
          page: "ジャンルページ（一覧・詳細）",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "432",
          page: "カテゴリページ（一覧・詳細）",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "433",
          page: "選び方ページ - 縦走用アックスの選び方",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "434",
          page: "選び方ページ -登山用軽量ハーネスの活用",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "435",
          page: "選び方ページ -アルトテント/テロステント",
          process: "SPコーディング修正版提出&確認確定",
        },
        { taskNo: "436", page: "新着商品", process: "SPコーディング提出" },
        { taskNo: "438", page: "キャンペーン", process: "SPコーディング提出" },
        { taskNo: "440", page: "限定アイテム", process: "SPコーディング提出" },
        { taskNo: "442", page: "Tech Info TOP", process: "SPコーディング提出" },
        {
          taskNo: "444",
          page: "Tech Info 一覧",
          process: "SPコーディング提出",
        },
        {
          taskNo: "446",
          page: "Tech Info詳細",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "447",
          page: "Tech Info 製品別 一覧",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "448",
          page: "Tech Info 製品別 詳細",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "449",
          page: "商品詳細",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "450",
          page: "マイページ",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "451",
          page: "ご利用にあたって",
          process: "PCコーディング提出",
        },
        {
          taskNo: "453",
          page: "ご利用ガイド一覧",
          process: "PCコーディング提出",
        },
        {
          taskNo: "455",
          page: "ご利用ガイド詳細",
          process: "PCコーディング提出",
        },
        {
          taskNo: "457",
          page: "コーポレートTOP",
          process: "PCコーディング提出",
        },
        { taskNo: "459", page: "会社情報", process: "PCコーディング提出" },
        {
          taskNo: "461",
          page: "会社情報詳細",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "462",
          page: "取扱店",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "463",
          page: "取扱店一覧",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "464",
          page: "サポート情報",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "465",
          page: "取扱説明書一覧 (PDF)",
          process: "SPデザイン修正版提出&確認確定",
        },
        { taskNo: "466", page: "お問い合わせ", process: "SPデザイン提出" },
        { taskNo: "468", page: "ニュース", process: "SPデザイン提出" },
        { taskNo: "470", page: "重要なお知らせ", process: "SPデザイン提出" },
        { taskNo: "472", page: "ブランドTOPページ", process: "SPデザイン提出" },
        {
          taskNo: "474",
          page: "Black Diamondページ",
          process: "SPデザイン提出",
        },
        {
          taskNo: "476",
          page: "製品一覧",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "477",
          page: "ヒストリー",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "478",
          page: "Ospreyページ",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "479",
          page: "Scarpaページ",
          process: "PCデザイン修正版提出&確認確定",
        },
        {
          taskNo: "480",
          page: "Smartwoolページ",
          process: "PCデザイン修正版提出&確認確定",
        },
      ],
      weekTasks: [
        {
          taskNo: "437",
          page: "新着商品",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "439",
          page: "キャンペーン",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "441",
          page: "限定アイテム",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "443",
          page: "Tech Info TOP",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "445",
          page: "Tech Info 一覧",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "452",
          page: "ご利用にあたって",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "454",
          page: "ご利用ガイド一覧",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "456",
          page: "ご利用ガイド詳細",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "458",
          page: "コーポレートTOP",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "460",
          page: "会社情報",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "467",
          page: "お問い合わせ",
          process: "SPデザイン修正依頼提出",
        },
        { taskNo: "469", page: "ニュース", process: "SPデザイン修正依頼提出" },
        {
          taskNo: "471",
          page: "重要なお知らせ",
          process: "SPデザイン修正依頼提出",
        },
        {
          taskNo: "473",
          page: "ブランドTOPページ",
          process: "SPデザイン修正依頼提出",
        },
        {
          taskNo: "475",
          page: "Black Diamondページ",
          process: "SPデザイン修正依頼提出",
        },
      ],
      progress: { completed: 5, inProgress: 30, notStarted: 0 },
    },
    {
      meetingNo: 13,
      date: "2025/10/08(水)",
      meetingTasks: [
        {
          taskNo: "481",
          page: "新着商品",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "482",
          page: "キャンペーン",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "483",
          page: "限定アイテム",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "484",
          page: "Tech Info TOP",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "485",
          page: "Tech Info 一覧",
          process: "SPコーディング修正版提出&確認確定",
        },
        { taskNo: "486", page: "Tech Info詳細", process: "SPコーディング提出" },
        {
          taskNo: "488",
          page: "Tech Info 製品別 一覧",
          process: "SPコーディング提出",
        },
        {
          taskNo: "490",
          page: "Tech Info 製品別 詳細",
          process: "SPコーディング提出",
        },
        { taskNo: "492", page: "商品詳細", process: "SPコーディング提出" },
        { taskNo: "494", page: "マイページ", process: "SPコーディング提出" },
        {
          taskNo: "496",
          page: "ご利用にあたって",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "497",
          page: "ご利用ガイド一覧",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "498",
          page: "ご利用ガイド詳細",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "499",
          page: "コーポレートTOP",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "500",
          page: "会社情報",
          process: "PCコーディング修正版提出&確認確定",
        },
        { taskNo: "501", page: "会社情報詳細", process: "PCコーディング提出" },
        { taskNo: "503", page: "取扱店", process: "PCコーディング提出" },
        { taskNo: "505", page: "取扱店一覧", process: "PCコーディング提出" },
        { taskNo: "507", page: "サポート情報", process: "PCコーディング提出" },
        {
          taskNo: "509",
          page: "取扱説明書一覧 (PDF)",
          process: "PCコーディング提出",
        },
        {
          taskNo: "511",
          page: "お問い合わせ",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "512",
          page: "ニュース",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "513",
          page: "重要なお知らせ",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "514",
          page: "ブランドTOPページ",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "515",
          page: "Black Diamondページ",
          process: "SPデザイン修正版提出&確認確定",
        },
        { taskNo: "516", page: "製品一覧", process: "SPデザイン提出" },
        { taskNo: "518", page: "ヒストリー", process: "SPデザイン提出" },
        { taskNo: "520", page: "Ospreyページ", process: "SPデザイン提出" },
        { taskNo: "522", page: "Scarpaページ", process: "SPデザイン提出" },
        { taskNo: "524", page: "Smartwoolページ", process: "SPデザイン提出" },
      ],
      weekTasks: [
        {
          taskNo: "487",
          page: "Tech Info詳細",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "489",
          page: "Tech Info 製品別 一覧",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "491",
          page: "Tech Info 製品別 詳細",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "493",
          page: "商品詳細",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "495",
          page: "マイページ",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "502",
          page: "会社情報詳細",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "504",
          page: "取扱店",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "506",
          page: "取扱店一覧",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "508",
          page: "サポート情報",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "510",
          page: "取扱説明書一覧 (PDF)",
          process: "PCコーディング修正依頼提出",
        },
        { taskNo: "517", page: "製品一覧", process: "SPデザイン修正依頼提出" },
        {
          taskNo: "519",
          page: "ヒストリー",
          process: "SPデザイン修正依頼提出",
        },
        {
          taskNo: "521",
          page: "Ospreyページ",
          process: "SPデザイン修正依頼提出",
        },
        {
          taskNo: "523",
          page: "Scarpaページ",
          process: "SPデザイン修正依頼提出",
        },
        {
          taskNo: "525",
          page: "Smartwoolページ",
          process: "SPデザイン修正依頼提出",
        },
      ],
      progress: { completed: 10, inProgress: 25, notStarted: 0 },
    },
    {
      meetingNo: 14,
      date: "2025/10/15(水)",
      meetingTasks: [
        {
          taskNo: "526",
          page: "Tech Info詳細",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "527",
          page: "Tech Info 製品別 一覧",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "528",
          page: "Tech Info 製品別 詳細",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "529",
          page: "商品詳細",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "530",
          page: "マイページ",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "531",
          page: "ご利用にあたって",
          process: "SPコーディング提出",
        },
        {
          taskNo: "533",
          page: "ご利用ガイド一覧",
          process: "SPコーディング提出",
        },
        {
          taskNo: "535",
          page: "ご利用ガイド詳細",
          process: "SPコーディング提出",
        },
        {
          taskNo: "537",
          page: "コーポレートTOP",
          process: "SPコーディング提出",
        },
        { taskNo: "539", page: "会社情報", process: "SPコーディング提出" },
        {
          taskNo: "541",
          page: "会社情報詳細",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "542",
          page: "取扱店",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "543",
          page: "取扱店一覧",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "544",
          page: "サポート情報",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "545",
          page: "取扱説明書一覧 (PDF)",
          process: "PCコーディング修正版提出&確認確定",
        },
        { taskNo: "546", page: "お問い合わせ", process: "PCコーディング提出" },
        { taskNo: "548", page: "ニュース", process: "PCコーディング提出" },
        {
          taskNo: "550",
          page: "重要なお知らせ",
          process: "PCコーディング提出",
        },
        {
          taskNo: "552",
          page: "ブランドTOPページ",
          process: "PCコーディング提出",
        },
        {
          taskNo: "554",
          page: "Black Diamondページ",
          process: "PCコーディング提出",
        },
        {
          taskNo: "556",
          page: "製品一覧",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "557",
          page: "ヒストリー",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "558",
          page: "Ospreyページ",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "559",
          page: "Scarpaページ",
          process: "SPデザイン修正版提出&確認確定",
        },
        {
          taskNo: "560",
          page: "Smartwoolページ",
          process: "SPデザイン修正版提出&確認確定",
        },
      ],
      weekTasks: [
        {
          taskNo: "532",
          page: "ご利用にあたって",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "534",
          page: "ご利用ガイド一覧",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "536",
          page: "ご利用ガイド詳細",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "538",
          page: "コーポレートTOP",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "540",
          page: "会社情報",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "547",
          page: "お問い合わせ",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "549",
          page: "ニュース",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "551",
          page: "重要なお知らせ",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "553",
          page: "ブランドTOPページ",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "555",
          page: "Black Diamondページ",
          process: "PCコーディング修正依頼提出",
        },
      ],
      progress: { completed: 15, inProgress: 20, notStarted: 0 },
    },
    {
      meetingNo: 15,
      date: "2025/10/22(水)",
      meetingTasks: [
        {
          taskNo: "561",
          page: "ご利用にあたって",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "562",
          page: "ご利用ガイド一覧",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "563",
          page: "ご利用ガイド詳細",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "564",
          page: "コーポレートTOP",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "565",
          page: "会社情報",
          process: "SPコーディング修正版提出&確認確定",
        },
        { taskNo: "566", page: "会社情報詳細", process: "SPコーディング提出" },
        { taskNo: "568", page: "取扱店", process: "SPコーディング提出" },
        { taskNo: "570", page: "取扱店一覧", process: "SPコーディング提出" },
        { taskNo: "572", page: "サポート情報", process: "SPコーディング提出" },
        {
          taskNo: "574",
          page: "取扱説明書一覧 (PDF)",
          process: "SPコーディング提出",
        },
        {
          taskNo: "576",
          page: "お問い合わせ",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "577",
          page: "ニュース",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "578",
          page: "重要なお知らせ",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "579",
          page: "ブランドTOPページ",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "580",
          page: "Black Diamondページ",
          process: "PCコーディング修正版提出&確認確定",
        },
        { taskNo: "581", page: "製品一覧", process: "PCコーディング提出" },
        { taskNo: "583", page: "ヒストリー", process: "PCコーディング提出" },
        { taskNo: "585", page: "Ospreyページ", process: "PCコーディング提出" },
        { taskNo: "587", page: "Scarpaページ", process: "PCコーディング提出" },
        {
          taskNo: "589",
          page: "Smartwoolページ",
          process: "PCコーディング提出",
        },
      ],
      weekTasks: [
        {
          taskNo: "567",
          page: "会社情報詳細",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "569",
          page: "取扱店",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "571",
          page: "取扱店一覧",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "573",
          page: "サポート情報",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "575",
          page: "取扱説明書一覧 (PDF)",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "582",
          page: "製品一覧",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "584",
          page: "ヒストリー",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "586",
          page: "Ospreyページ",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "588",
          page: "Scarpaページ",
          process: "PCコーディング修正依頼提出",
        },
        {
          taskNo: "590",
          page: "Smartwoolページ",
          process: "PCコーディング修正依頼提出",
        },
      ],
      progress: { completed: 20, inProgress: 15, notStarted: 0 },
    },
    {
      meetingNo: 16,
      date: "2025/10/29(水)",
      meetingTasks: [
        {
          taskNo: "591",
          page: "会社情報詳細",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "592",
          page: "取扱店",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "593",
          page: "取扱店一覧",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "594",
          page: "サポート情報",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "595",
          page: "取扱説明書一覧 (PDF)",
          process: "SPコーディング修正版提出&確認確定",
        },
        { taskNo: "596", page: "お問い合わせ", process: "SPコーディング提出" },
        { taskNo: "598", page: "ニュース", process: "SPコーディング提出" },
        {
          taskNo: "600",
          page: "重要なお知らせ",
          process: "SPコーディング提出",
        },
        {
          taskNo: "602",
          page: "ブランドTOPページ",
          process: "SPコーディング提出",
        },
        {
          taskNo: "604",
          page: "Black Diamondページ",
          process: "SPコーディング提出",
        },
        {
          taskNo: "606",
          page: "製品一覧",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "607",
          page: "ヒストリー",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "608",
          page: "Ospreyページ",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "609",
          page: "Scarpaページ",
          process: "PCコーディング修正版提出&確認確定",
        },
        {
          taskNo: "610",
          page: "Smartwoolページ",
          process: "PCコーディング修正版提出&確認確定",
        },
      ],
      weekTasks: [
        {
          taskNo: "597",
          page: "お問い合わせ",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "599",
          page: "ニュース",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "601",
          page: "重要なお知らせ",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "603",
          page: "ブランドTOPページ",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "605",
          page: "Black Diamondページ",
          process: "SPコーディング修正依頼提出",
        },
      ],
      progress: { completed: 25, inProgress: 10, notStarted: 0 },
    },
    {
      meetingNo: 17,
      date: "2025/11/05(水)",
      meetingTasks: [
        {
          taskNo: "611",
          page: "お問い合わせ",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "612",
          page: "ニュース",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "613",
          page: "重要なお知らせ",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "614",
          page: "ブランドTOPページ",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "615",
          page: "Black Diamondページ",
          process: "SPコーディング修正版提出&確認確定",
        },
        { taskNo: "616", page: "製品一覧", process: "SPコーディング提出" },
        { taskNo: "618", page: "ヒストリー", process: "SPコーディング提出" },
        { taskNo: "620", page: "Ospreyページ", process: "SPコーディング提出" },
        { taskNo: "622", page: "Scarpaページ", process: "SPコーディング提出" },
        {
          taskNo: "624",
          page: "Smartwoolページ",
          process: "SPコーディング提出",
        },
      ],
      weekTasks: [
        {
          taskNo: "617",
          page: "製品一覧",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "619",
          page: "ヒストリー",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "621",
          page: "Ospreyページ",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "623",
          page: "Scarpaページ",
          process: "SPコーディング修正依頼提出",
        },
        {
          taskNo: "625",
          page: "Smartwoolページ",
          process: "SPコーディング修正依頼提出",
        },
      ],
      progress: { completed: 30, inProgress: 5, notStarted: 0 },
    },
    {
      meetingNo: 18,
      date: "2025/11/12(水)",
      meetingTasks: [
        {
          taskNo: "626",
          page: "製品一覧",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "627",
          page: "ヒストリー",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "628",
          page: "Ospreyページ",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "629",
          page: "Scarpaページ",
          process: "SPコーディング修正版提出&確認確定",
        },
        {
          taskNo: "630",
          page: "Smartwoolページ",
          process: "SPコーディング修正版提出&確認確定",
        },
      ],
      weekTasks: [],
      progress: { completed: 35, inProgress: 0, notStarted: 0 },
    },
  ],
};
